version: 0.2

phases:
  install:
    commands:
      - npm install --production
  build:
    commands:
      - echo "Build step (opcional) finalizado."
artifacts:
  base-directory: .
  files:
    - "**/*"
  discard-paths: no
  exclude-files:
    - "**/test/**"
    - "**/tests/**"
    - "**/*.md"
    - "**/.git/**"