version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Build step (opcional) finalizado."
artifacts:
  base-directory: .
  files:
    - "**/*"
  discard-paths: no